<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="applicabilitymodel" nsURI="http://applicabilitymodel/applicabilitymodel"
    nsPrefix="applicabilitymodel">
  <eClassifiers xsi:type="ecore:EClass" name="ApplicabilityModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualitymodel" lowerBound="1"
        eType="#//InputModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentSetStore" lowerBound="1"
        eType="#//InputModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicabilities" lowerBound="1"
        upperBound="-1" eType="#//Applicability" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Applicability">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualityScenario" lowerBound="1"
        eType="#//QualityScenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentSets" upperBound="-1"
        eType="#//ComponentSet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualityScenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
